(define (problem cleaner-problem)
    (:domain cleaner-domain)
    (:objects r v m s0 s1 kitchen bedroom sr attic f00 f01 f10
            f12 f21)
    (:init
        (robot r)(vacuum v)(mop m)
        (stairs s0)(stairs s1)
        (room attic)(room sr)(room bedroom)(room kitchen)
        (loc s0)(loc s1)(loc attic)
        (loc sr)(loc bedroom)(loc kitchen)
        (loc f01)(loc f00)(loc f10)(loc f12)(loc f21)
        (adj kitchen f01)(adj f01 kitchen)
        (adj f01 f00)(adj f00 f01)
        (adj f00 s0)(adj s0 f00)
        (adj s0 f12)(adj f12 s0)
        (adj f12 bedroom)(adj bedroom f12)
        (adj bedroom f10)(adj f10 bedroom)
        (adj s1 f12)(adj f12 s1)
        (adj attic s1)(adj s1 attic)
        (adj f21 attic)(adj attic f21)
        (adj sr f21)(adj f21 sr)
        (at r f01)(at v f10)(at m f21)
        (object m)(object v)
        (free r)
        (dirty kitchen)(dirty s0)(dirty bedroom)
        (dirty attic)(dirty s1)
        (above f12 s0)(above attic s1)
    )
    (:goal
        (and(not(dirty kitchen))
            (not(dirty s0))
            (not(dirty bedroom))
            (not(dirty s1))
            (not(dirty attic))
            (at m sr)
            (at v sr)
        )
    )
)